CREATE TABLE `payment` (
    `user_id` INT UNSIGNED PRIMARY KEY,
    `gem` INT UNSIGNED NOT NULL DEFAULT 0,
    `gold` INT UNSIGNED NOT NULL DEFAULT 0,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);